// Copyright 2017 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_mpsi_control_in                 15
#define gattdb_mpsi_message_in                 17
#define gattdb_mpsi_control_out                19
#define gattdb_mpsi_message_out                22
#define gattdb_ota_control                     25
#define gattdb_ota_data                        27

#endif
