// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __MPSI_CONFIGURATION__
#define __MPSI_CONFIGURATION__

// Generated message IDs
#define MPSI_MESSAGE_ID_INCLUDE_GET_APPS_INFO 0x0000
#define MPSI_MESSAGE_ID_INCLUDE_APPS_INFO 0x0001
#define MPSI_MESSAGE_ID_INCLUDE_BOOTLOAD_SLOT 0x0002
#define MPSI_MESSAGE_ID_INCLUDE_ERROR 0x0003
#define MPSI_MESSAGE_ID_INCLUDE_INITIATE_JOINING 0x0004
#define MPSI_MESSAGE_ID_INCLUDE_GET_ZIGBEE_JOINING_DEVICE_INFO 0x0005
#define MPSI_MESSAGE_ID_INCLUDE_ZIGBEE_JOINING_DEVICE_INFO 0x0006
#define MPSI_MESSAGE_ID_INCLUDE_SET_ZIGBEE_JOINING_DEVICE_INFO 0x0007
#define MPSI_MESSAGE_ID_INCLUDE_GET_ZIGBEE_TRUST_CENTER_JOINING_CREDENTIALS 0x0008
#define MPSI_MESSAGE_ID_INCLUDE_ZIGBEE_TRUST_CENTER_JOINING_CREDENTIALS 0x0009
#define MPSI_MESSAGE_ID_INCLUDE_SET_ZIGBEE_TRUST_CENTER_JOINING_CREDENTIALS 0x000A

// Generated function mapping
#define MPSI_GENERATED_FUNCTION_MAP                                                                                                   \
  {                                                                                                                                   \
    { MPSI_MESSAGE_ID_INCLUDE_GET_APPS_INFO, mpsiHandleMessageGetAppsInfo },                                                          \
    { MPSI_MESSAGE_ID_INCLUDE_APPS_INFO, mpsiHandleMessageAppsInfo },                                                                 \
    { MPSI_MESSAGE_ID_INCLUDE_BOOTLOAD_SLOT, mpsiHandleMessageBootloadSlot },                                                         \
    { MPSI_MESSAGE_ID_INCLUDE_ERROR, mpsiHandleMessageError },                                                                        \
    { MPSI_MESSAGE_ID_INCLUDE_INITIATE_JOINING, mpsiHandleMessageInitiateJoining },                                                   \
    { MPSI_MESSAGE_ID_INCLUDE_GET_ZIGBEE_JOINING_DEVICE_INFO, mpsiHandleMessageGetZigbeeJoiningDeviceInfo },                          \
    { MPSI_MESSAGE_ID_INCLUDE_ZIGBEE_JOINING_DEVICE_INFO, mpsiHandleMessageZigbeeJoiningDeviceInfo },                                 \
    { MPSI_MESSAGE_ID_INCLUDE_SET_ZIGBEE_JOINING_DEVICE_INFO, mpsiHandleMessageSetZigbeeJoiningDeviceInfo },                          \
    { MPSI_MESSAGE_ID_INCLUDE_GET_ZIGBEE_TRUST_CENTER_JOINING_CREDENTIALS, mpsiHandleMessageGetZigbeeTrustCenterJoiningCredentials }, \
    { MPSI_MESSAGE_ID_INCLUDE_ZIGBEE_TRUST_CENTER_JOINING_CREDENTIALS, mpsiHandleMessageZigbeeTrustCenterJoiningCredentials },        \
    { MPSI_MESSAGE_ID_INCLUDE_SET_ZIGBEE_TRUST_CENTER_JOINING_CREDENTIALS, mpsiHandleMessageSetZigbeeTrustCenterJoiningCredentials }, \
  }

#endif // __MPSI_CONFIGURATION__
