// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED.
// See the script gen-api-macro-header and read gen-api-macro-header.README.

#ifndef DEFINE_EMBER_API_H
#define DEFINE_EMBER_API_H

#if (!defined (RTOS) || !defined (IP_MODEM_LIBRARY))   // non RTOS targets and RTOS host thread

  #define emApiAbortWakeup emberAbortWakeup
  #define emApiAbortWakeupReturn emberAbortWakeupReturn
  #define emApiActiveScanHandler emberActiveScanHandler
  #define emApiActiveWakeup emberActiveWakeup
  #define emApiActiveWakeupReturn emberActiveWakeupReturn
  #define emApiAddAddressData emberAddAddressData
  #define emApiAddAddressDataReturn emberAddAddressDataReturn
  #define emApiAddressConfigurationChangeHandler emberAddressConfigurationChangeHandler
  #define emApiAddSteeringEui64 emberAddSteeringEui64
  #define emApiAllowNativeCommissioner emberAllowNativeCommissioner
  #define emApiAllowNativeCommissionerReturn emberAllowNativeCommissionerReturn
  #define emApiAppEventQueue emberAppEventQueue
  #define emApiAppEvents emberAppEvents
  #define emApiAssertInfoReturn emberAssertInfoReturn
  #define emApiAttachToNetwork emberAttachToNetwork
  #define emApiAttachToNetworkReturn emberAttachToNetworkReturn
  #define emApiBecomeCommissioner emberBecomeCommissioner
  #define emApiBecomeCommissionerReturn emberBecomeCommissionerReturn
  #define emApiChangeNodeType emberChangeNodeType
  #define emApiChangeNodeTypeReturn emberChangeNodeTypeReturn
  #define emApiClearAddressCache emberClearAddressCache
  #define emApiClearAddressCacheReturn emberClearAddressCacheReturn
  #define emApiClearCounters emberClearCounters
  #define emApiCloseDtlsConnection emberCloseDtlsConnection
  #define emApiCloseDtlsConnectionReturn emberCloseDtlsConnectionReturn
  #define emApiCoapMessageHandler emberCoapMessageHandler
  #define emApiCoapRequestHandler emberCoapRequestHandler
  #define emApiCommandTable emberCommandTable
  #define emApiCommissionerStatusHandler emberCommissionerStatusHandler
  #define emApiCommissionNetwork emberCommissionNetwork
  #define emApiCommissionNetworkReturn emberCommissionNetworkReturn
  #define emApiConfigUart emberConfigUart
  #define emApiConfigUartReturn emberConfigUartReturn
  #define emApiConfigureExternalRoute emberConfigureExternalRoute
  #define emApiConfigureExternalRouteReturn emberConfigureExternalRouteReturn
  #define emApiConfigureGateway emberConfigureGateway
  #define emApiConfigureGatewayReturn emberConfigureGatewayReturn
  #define emApiConfigureNetwork emberConfigureNetwork
  #define emApiConfigureWakeup emberConfigureWakeup
  #define emApiCounterHandler emberCounterHandler
  #define emApiCounterValueHandler emberCounterValueHandler
  #define emApiCustomHostToNcpMessage emberCustomHostToNcpMessage
  #define emApiCustomHostToNcpMessageHandler emberCustomHostToNcpMessageHandler
  #define emApiCustomNcpToHostMessage emberCustomNcpToHostMessage
  #define emApiCustomNcpToHostMessageHandler emberCustomNcpToHostMessageHandler
  #define emApiDeepSleep emberDeepSleep
  #define emApiDeepSleepCompleteHandler emberDeepSleepCompleteHandler
  #define emApiDeepSleepReturn emberDeepSleepReturn
  #define emApiDhcpServerChangeHandler emberDhcpServerChangeHandler
  #define emApiDiagnosticAnswerHandler emberDiagnosticAnswerHandler
  #define emApiDtlsSecureSessionEstablished emberDtlsSecureSessionEstablished
  #define emApiEcho emberEcho
  #define emApiEchoReturn emberEchoReturn
  #define emApiEnableHostDtlsClient emberEnableHostDtlsClient
  #define emApiEnableResetNcpGpio emberEnableResetNcpGpio
  #define emApiEnergyScanHandler emberEnergyScanHandler
  #define emApiEui64 emberEui64
  #define emApiEventDelayUpdatedFromIsrHandler emberEventDelayUpdatedFromIsrHandler
  #define emApiExternalRouteChangeHandler emberExternalRouteChangeHandler
  #define emApiFfWakeup emberFfWakeup
  #define emApiFinishCoapMessage emberFinishCoapMessage
  #define emApiForceAssert emberForceAssert
  #define emApiFormNetwork emberFormNetwork
  #define emApiFormNetworkReturn emberFormNetworkReturn
  #define emApiGetAntennaMode emberGetAntennaMode
  #define emApiGetAntennaModeReturn emberGetAntennaModeReturn
  #define emApiGetCcaThreshold emberGetCcaThreshold
  #define emApiGetCcaThresholdReturn emberGetCcaThresholdReturn
  #define emApiGetChannelCalDataTokenReturn emberGetChannelCalDataTokenReturn
  #define emApiGetCommissioner emberGetCommissioner
  #define emApiGetCounter emberGetCounter
  #define emApiGetCounterReturn emberGetCounterReturn
  #define emApiGetCtune emberGetCtune
  #define emApiGetCtuneReturn emberGetCtuneReturn
  #define emApiGetGlobalAddresses emberGetGlobalAddresses
  #define emApiGetGlobalAddressReturn emberGetGlobalAddressReturn
  #define emApiGetGlobalPrefixes emberGetGlobalPrefixes
  #define emApiGetGlobalPrefixReturn emberGetGlobalPrefixReturn
  #define emApiGetIndexedToken emberGetIndexedToken
  #define emApiGetLocalIpAddress emberGetLocalIpAddress
  #define emApiGetMfgToken emberGetMfgToken
  #define emApiGetMfgTokenReturn emberGetMfgTokenReturn
  #define emApiGetMulticastEntryReturn emberGetMulticastEntryReturn
  #define emApiGetMulticastTable emberGetMulticastTable
  #define emApiGetNetworkData emberGetNetworkData
  #define emApiGetNetworkDataReturn emberGetNetworkDataReturn
  #define emApiGetNetworkDataTlv emberGetNetworkDataTlv
  #define emApiGetNetworkDataTlvReturn emberGetNetworkDataTlvReturn
  #define emApiGetNetworkKeyInfo emberGetNetworkKeyInfo
  #define emApiGetNetworkKeyInfoReturn emberGetNetworkKeyInfoReturn
  #define emApiGetNetworkParameters emberGetNetworkParameters
  #define emApiGetNodeStatus emberGetNodeStatus
  #define emApiGetNodeStatusReturn emberGetNodeStatusReturn
  #define emApiGetPanId emberGetPanId
  #define emApiGetPtaEnable emberGetPtaEnable
  #define emApiGetPtaEnableReturn emberGetPtaEnableReturn
  #define emApiGetPtaOptions emberGetPtaOptions
  #define emApiGetPtaOptionsReturn emberGetPtaOptionsReturn
  #define emApiGetRadioPower emberGetRadioPower
  #define emApiGetRadioPowerReturn emberGetRadioPowerReturn
  #define emApiGetRipEntry emberGetRipEntry
  #define emApiGetRipEntryReturn emberGetRipEntryReturn
  #define emApiGetRoutingLocator emberGetRoutingLocator
  #define emApiGetRoutingLocatorReturn emberGetRoutingLocatorReturn
  #define emApiGetSecureDtlsSessionId emberGetSecureDtlsSessionId
  #define emApiGetSecureDtlsSessionIdReturn emberGetSecureDtlsSessionIdReturn
  #define emApiGetStandaloneBootloaderInfo emberGetStandaloneBootloaderInfo
  #define emApiGetStandaloneBootloaderInfoReturn emberGetStandaloneBootloaderInfoReturn
  #define emApiGetTxPowerMode emberGetTxPowerMode
  #define emApiGetTxPowerModeReturn emberGetTxPowerModeReturn
  #define emApiGetVersions emberGetVersions
  #define emApiGetVersionsReturn emberGetVersionsReturn
  #define emApiGpioCurrentConfig emberGpioCurrentConfig
  #define emApiGpioCurrentConfigReturn emberGpioCurrentConfigReturn
  #define emApiGpioCurrentInput emberGpioCurrentInput
  #define emApiGpioCurrentInputReturn emberGpioCurrentInputReturn
  #define emApiGpioPowerConfig emberGpioPowerConfig
  #define emApiGpioPowerConfigReturn emberGpioPowerConfigReturn
  #define emApiGpioRadioPowerMask emberGpioRadioPowerMask
  #define emApiHostStateHandler emberHostStateHandler
  #define emApiHostToNcpNoOp emberHostToNcpNoOp
  #define emApiIcmpListen emberIcmpListen
  #define emApiIncomingIcmpHandler emberIncomingIcmpHandler
  #define emApiInit emberInit
  #define emApiInitHost emberInitHost
  #define emApiInitReturn emberInitReturn
  #define emApiIpPing emberIpPing
  #define emApiJoinCommissioned emberJoinCommissioned
  #define emApiJoinNetwork emberJoinNetwork
  #define emApiJoinNetworkReturn emberJoinNetworkReturn
  #define emApiLaunchStandaloneBootloader emberLaunchStandaloneBootloader
  #define emApiLaunchStandaloneBootloaderReturn emberLaunchStandaloneBootloaderReturn
  #define emApiLeaderDataHandler emberLeaderDataHandler
  #define emApiListenForWakeup emberListenForWakeup
  #define emApiListenForWakeupReturn emberListenForWakeupReturn
  #define emApiLookupAddressData emberLookupAddressData
  #define emApiLookupAddressDataReturn emberLookupAddressDataReturn
  #define emApiMacPassthroughFilterHandler emberMacPassthroughFilterHandler
  #define emApiMacPassthroughMessageHandler emberMacPassthroughMessageHandler
  #define emApiMacRssiFilterHandler emberMacRssiFilterHandler
  #define emApiMacRssiHandler emberMacRssiHandler
  #define emApiMarkApplicationBuffersHandler emberMarkApplicationBuffersHandler
  #define emApiNcpToHostNoOp emberNcpToHostNoOp
  #define emApiNcpUdpStorm emberNcpUdpStorm
  #define emApiNcpUdpStormCompleteHandler emberNcpUdpStormCompleteHandler
  #define emApiNcpUdpStormReturn emberNcpUdpStormReturn
  #define emApiNetworkDataChangeHandler emberNetworkDataChangeHandler
  #define emApiNetworkStatus emberNetworkStatus
  #define emApiNetworkStatusHandler emberNetworkStatusHandler
  #define emApiOkToNap emberOkToNap
  #define emApiOkToNapReturn emberOkToNapReturn
  #define emApiOpenDtlsConnection emberOpenDtlsConnection
  #define emApiOpenDtlsConnectionReturn emberOpenDtlsConnectionReturn
  #define emApiHostJoinClientComplete emberHostJoinClientComplete
  #define emApiPermitJoining emberPermitJoining
  #define emApiPermitJoiningHandler emberPermitJoiningHandler
  #define emApiPermitJoiningReturn emberPermitJoiningReturn
  #define emApiPing emberPing
  #define emApiPollForData emberPollForData
  #define emApiPollForDataReturn emberPollForDataReturn
  #define emApiRadioGetRandomNumbers emberRadioGetRandomNumbers
  #define emApiRadioGetRandomNumbersReturn emberRadioGetRandomNumbersReturn
  #define emApiRegisterDropIncomingMessageCallback emberRegisterDropIncomingMessageCallback
  #define emApiRegisterSerialTransmitCallback emberRegisterSerialTransmitCallback
  #define emApiRequestDhcpAddress emberRequestDhcpAddress
  #define emApiRequestDhcpAddressReturn emberRequestDhcpAddressReturn
  #define emApiRequestSlaacAddress emberRequestSlaacAddress
  #define emApiRequestSlaacAddressReturn emberRequestSlaacAddressReturn
  #define emApiResetIpDriverAsh emberResetIpDriverAsh
  #define emApiResetMicro emberResetMicro
  #define emApiResetMicroHandler emberResetMicroHandler
  #define emApiResetNcpAsh emberResetNcpAsh
  #define emApiResetNcpAshReturn emberResetNcpAshReturn
  #define emApiResetNcpGpio emberResetNcpGpio
  #define emApiResetNetworkState emberResetNetworkState
  #define emApiResetNetworkStateReturn emberResetNetworkStateReturn
  #define emApiResignGlobalAddress emberResignGlobalAddress
  #define emApiResignGlobalAddressReturn emberResignGlobalAddressReturn
  #define emApiResumeNetwork emberResumeNetwork
  #define emApiResumeNetworkReturn emberResumeNetworkReturn
  #define emApiRetryCoapMessage emberRetryCoapMessage
  #define emApiScanReturn emberScanReturn
  #define emApiSendDone emberSendDone
  #define emApiSendDoneReturn emberSendDoneReturn
  #define emApiSendSteeringData emberSendSteeringData
  #define emApiSendSteeringDataReturn emberSendSteeringDataReturn
  #define emApiSendUdp emberSendUdp
  #define emApiSetAddressHandler emberSetAddressHandler
  #define emApiSetCcaThreshold emberSetCcaThreshold
  #define emApiSetCcaThresholdReturn emberSetCcaThresholdReturn
  #define emApiSetClockMonitor emberSetClockMonitor
  #define emApiSetCommProxyAppAddressHandler emberSetCommProxyAppAddressHandler
  #define emApiSetCommProxyAppPskcHandler emberSetCommProxyAppPskcHandler
  #define emApiSetCommProxyAppParametersHandler emberSetCommProxyAppParametersHandler
  #define emApiSetCommProxyAppSecurityHandler emberSetCommProxyAppSecurityHandler
  #define emApiSetCommissionerKey emberSetCommissionerKey
  #define emApiSetCommissionerKeyReturn emberSetCommissionerKeyReturn
  #define emApiSetCtune emberSetCtune
  #define emApiSetCtuneReturn emberSetCtuneReturn
  #define emApiSetDriverAddressHandler emberSetDriverAddressHandler
  #define emApiSetDtlsDeviceCertificate emberSetDtlsDeviceCertificate
  #define emApiSetDtlsDeviceCertificateReturn emberSetDtlsDeviceCertificateReturn
  #define emApiSetDtlsPresharedKey emberSetDtlsPresharedKey
  #define emApiSetDtlsPresharedKeyReturn emberSetDtlsPresharedKeyReturn
  #define emApiSetEui64 emberSetEui64
  #define emApiSetAntennaMode emberSetAntennaMode
  #define emApiSetAntennaModeReturn emberSetAntennaModeReturn
  #define emApiSetJoiningMode emberSetJoiningMode
  #define emApiSetJoinKey emberSetJoinKey
  #define emApiSetJoinKeyReturn emberSetJoinKeyReturn
  #define emApiSetLegacyFilterMaxThreshold emberSetLegacyFilterMaxThreshold
  #define emApiSetLegacyFilterMaxThresholdReturn emberSetLegacyFilterMaxThresholdReturn
  #define emApiSetLegacyFilterMinThreshold emberSetLegacyFilterMinThreshold
  #define emApiSetLegacyFilterMinThresholdReturn emberSetLegacyFilterMinThresholdReturn
  #define emApiSetLocalNetworkData emberSetLocalNetworkData
  #define emApiSetLocalNetworkDataReturn emberSetLocalNetworkDataReturn
  #define emApiSetMfgToken emberSetMfgToken
  #define emApiSetMfgTokenReturn emberSetMfgTokenReturn
  #define emApiSetNdData emberSetNdData
  #define emApiSetNdDataReturn emberSetNdDataReturn
  #define emApiSetNetworkKeysHandler emberSetNetworkKeysHandler
  #define emApiSetNextNetworkKey emberSetNextNetworkKey
  #define emApiSetNextNetworkKeyReturn emberSetNextNetworkKeyReturn
  #define emApiSetPassthroughPort emberSetPassthroughPort
  #define emApiSetPskcHandler emberSetPskcHandler
  #define emApiSetPtaEnable emberSetPtaEnable
  #define emApiSetPtaEnableReturn emberSetPtaEnableReturn
  #define emApiSetPtaOptions emberSetPtaOptions
  #define emApiSetPtaOptionsReturn emberSetPtaOptionsReturn
  #define emApiSetRadioHoldOff emberSetRadioHoldOff
  #define emApiSetRadioHoldOffReturn emberSetRadioHoldOffReturn
  #define emApiSetRadioPower emberSetRadioPower
  #define emApiSetRadioPowerReturn emberSetRadioPowerReturn
  #define emApiSetRandomizeMacExtendedId emberSetRandomizeMacExtendedId
  #define emApiSetSecurityParameters emberSetSecurityParameters
  #define emApiSetSecurityParametersReturn emberSetSecurityParametersReturn
  #define emApiSetTxPowerMode emberSetTxPowerMode
  #define emApiSetTxPowerModeReturn emberSetTxPowerModeReturn
  #define emApiSetWakeupSequenceNumber emberSetWakeupSequenceNumber
  #define emApiSetWakeupSequenceNumberReturn emberSetWakeupSequenceNumberReturn
  #define emApiSlaacServerChangeHandler emberSlaacServerChangeHandler
  #define emApiSleepNoTimer emberSleepNoTimer
  #define emApiSleepNoTimerReturn emberSleepNoTimerReturn
  #define emApiStackIdleTimeMs emberStackIdleTimeMs
  #define emApiStackPollForData emberStackPollForData
  #define emApiStackPollForDataReturn emberStackPollForDataReturn
  #define emApiStartHostJoinClientHandler emberStartHostJoinClientHandler
  #define emApiStartScan emberStartScan
  #define emApiStartUartSpeedTest emberStartUartSpeedTest
  #define emApiStartUartStorm emberStartUartStorm
  #define emApiStartUartStormReturn emberStartUartStormReturn
  #define emApiStartWakeup emberStartWakeup
  #define emApiStartWakeupReturn emberStartWakeupReturn
  #define emApiStartXOnXOffTest emberStartXOnXOffTest
  #define emApiState emberState
  #define emApiStateReturn emberStateReturn
  #define emApiStopCommissioning emberStopCommissioning
  #define emApiStopScan emberStopScan
  #define emApiStopUartStorm emberStopUartStorm
  #define emApiStopUartStormReturn emberStopUartStormReturn
  #define emApiSwitchToNextNetworkKey emberSwitchToNextNetworkKey
  #define emApiSwitchToNextNetworkKeyHandler emberSwitchToNextNetworkKeyHandler
  #define emApiSwitchToNextNetworkKeyReturn emberSwitchToNextNetworkKeyReturn
  #define emApiTick emberTick
  #define emApiUartSpeedTestReturn emberUartSpeedTestReturn
  #define emApiUdpHandler emberUdpHandler
  #define emApiUdpListen emberUdpListen
  #define emApiUdpMulticastHandler emberUdpMulticastHandler
  #define emApiWakeupHandler emberWakeupHandler
  #define emApiWakeupState emberWakeupState
  #define emApiWakeupStateReturn emberWakeupStateReturn
  #define mfglibApiEnd mfglibEnd
  #define mfglibApiGetChannel mfglibGetChannel
  #define mfglibApiGetOptions mfglibGetOptions
  #define mfglibApiGetPower mfglibGetPower
  #define mfglibApiGetPowerMode mfglibGetPowerMode
  #define mfglibApiGetSynOffset mfglibGetSynOffset
  #define mfglibApiSendPacket mfglibSendPacket
  #define mfglibApiSetChannel mfglibSetChannel
  #define mfglibApiSetOptions mfglibSetOptions
  #define mfglibApiSetPower mfglibSetPower
  #define mfglibApiSetSynOffset mfglibSetSynOffset
  #define mfglibApiStart mfglibStart
  #define mfglibApiStartStream mfglibStartStream
  #define mfglibApiStartTone mfglibStartTone
  #define mfglibApiStopStream mfglibStopStream
  #define mfglibApiStopTone mfglibStopTone
  #define mfglibApiTestContModCal mfglibTestContModCal
  #define emStackNoteExternalCommissioner emNoteExternalCommissioner
  #define emStackIpPing emIpPing
  #define tmspNcpMfglibEnd tmspMfglibEnd
  #define tmspNcpMfglibEndTestReturn tmspMfglibEndTestReturn
  #define tmspNcpMfglibGet tmspMfglibGet
  #define tmspNcpMfglibGetChannelReturn tmspMfglibGetChannelReturn
  #define tmspNcpMfglibGetOptionsReturn tmspMfglibGetOptionsReturn
  #define tmspNcpMfglibGetPowerModeReturn tmspMfglibGetPowerModeReturn
  #define tmspNcpMfglibGetPowerReturn tmspMfglibGetPowerReturn
  #define tmspNcpMfglibGetSynOffsetReturn tmspMfglibGetSynOffsetReturn
  #define tmspNcpMfglibRxReturn tmspMfglibRxReturn
  #define tmspNcpMfglibSendPacket tmspMfglibSendPacket
  #define tmspNcpMfglibSendPacketEventHandler tmspMfglibSendPacketEventHandler
  #define tmspNcpMfglibSet tmspMfglibSet
  #define tmspNcpMfglibSetReturn tmspMfglibSetReturn
  #define tmspNcpMfglibStart tmspMfglibStart
  #define tmspNcpMfglibStartActivity tmspMfglibStartActivity
  #define tmspNcpMfglibStartReturn tmspMfglibStartReturn
  #define tmspNcpMfglibStartTestReturn tmspMfglibStartTestReturn
  #define tmspNcpMfglibStopActivity tmspMfglibStopActivity
  #define tmspNcpMfglibStopReturn tmspMfglibStopReturn
  #define tmspNcpMfglibTestContModCal tmspMfglibTestContModCal

#elif IP_MODEM_LIBRARY // NCP thread in RTOS target

  #define emberAbortWakeup emApiAbortWakeup
  #define emberAbortWakeupReturn emApiAbortWakeupReturn
  #define emberActiveScanHandler emApiActiveScanHandler
  #define emberActiveWakeup emApiActiveWakeup
  #define emberActiveWakeupReturn emApiActiveWakeupReturn
  #define emberAddAddressData emApiAddAddressData
  #define emberAddAddressDataReturn emApiAddAddressDataReturn
  #define emberAddressConfigurationChangeHandler emApiAddressConfigurationChangeHandler
  #define emberAddSteeringEui64 emApiAddSteeringEui64
  #define emberAllowNativeCommissioner emApiAllowNativeCommissioner
  #define emberAllowNativeCommissionerReturn emApiAllowNativeCommissionerReturn
  #define emberAppEventQueue emApiAppEventQueue
  #define emberAppEvents emApiAppEvents
  #define emberAssertInfoReturn emApiAssertInfoReturn
  #define emberAttachToNetwork emApiAttachToNetwork
  #define emberAttachToNetworkReturn emApiAttachToNetworkReturn
  #define emberBecomeCommissioner emApiBecomeCommissioner
  #define emberBecomeCommissionerReturn emApiBecomeCommissionerReturn
  #define emberChangeNodeType emApiChangeNodeType
  #define emberChangeNodeTypeReturn emApiChangeNodeTypeReturn
  #define emberClearAddressCache emApiClearAddressCache
  #define emberClearAddressCacheReturn emApiClearAddressCacheReturn
  #define emberClearCounters emApiClearCounters
  #define emberCloseDtlsConnection emApiCloseDtlsConnection
  #define emberCloseDtlsConnectionReturn emApiCloseDtlsConnectionReturn
  #define emberCoapMessageHandler emApiCoapMessageHandler
  #define emberCoapRequestHandler emApiCoapRequestHandler
  #define emberCommandTable emApiCommandTable
  #define emberCommissionerStatusHandler emApiCommissionerStatusHandler
  #define emberCommissionNetwork emApiCommissionNetwork
  #define emberCommissionNetworkReturn emApiCommissionNetworkReturn
  #define emberConfigUart emApiConfigUart
  #define emberConfigUartReturn emApiConfigUartReturn
  #define emberConfigureExternalRoute emApiConfigureExternalRoute
  #define emberConfigureExternalRouteReturn emApiConfigureExternalRouteReturn
  #define emberConfigureGateway emApiConfigureGateway
  #define emberConfigureGatewayReturn emApiConfigureGatewayReturn
  #define emberConfigureNetwork emApiConfigureNetwork
  #define emberConfigureWakeup emApiConfigureWakeup
  #define emberCounterHandler emApiCounterHandler
  #define emberCounterValueHandler emApiCounterValueHandler
  #define emberCustomHostToNcpMessage emApiCustomHostToNcpMessage
  #define emberCustomHostToNcpMessageHandler emApiCustomHostToNcpMessageHandler
  #define emberCustomNcpToHostMessage emApiCustomNcpToHostMessage
  #define emberCustomNcpToHostMessageHandler emApiCustomNcpToHostMessageHandler
  #define emberDeepSleep emApiDeepSleep
  #define emberDeepSleepCompleteHandler emApiDeepSleepCompleteHandler
  #define emberDeepSleepReturn emApiDeepSleepReturn
  #define emberDhcpServerChangeHandler emApiDhcpServerChangeHandler
  #define emberDiagnosticAnswerHandler emApiDiagnosticAnswerHandler
  #define emberDtlsSecureSessionEstablished emApiDtlsSecureSessionEstablished
  #define emberEcho emApiEcho
  #define emberEchoReturn emApiEchoReturn
  #define emberEnableHostDtlsClient emApiEnableHostDtlsClient
  #define emberEnableResetNcpGpio emApiEnableResetNcpGpio
  #define emberEnergyScanHandler emApiEnergyScanHandler
  #define emberEui64 emApiEui64
  #define emberEventDelayUpdatedFromIsrHandler emApiEventDelayUpdatedFromIsrHandler
  #define emberExternalRouteChangeHandler emApiExternalRouteChangeHandler
  #define emberFfWakeup emApiFfWakeup
  #define emberFinishCoapMessage emApiFinishCoapMessage
  #define emberForceAssert emApiForceAssert
  #define emberFormNetwork emApiFormNetwork
  #define emberFormNetworkReturn emApiFormNetworkReturn
  #define emberGetAntennaMode emApiGetAntennaMode
  #define emberGetAntennaModeReturn emApiGetAntennaModeReturn
  #define emberGetCcaThreshold emApiGetCcaThreshold
  #define emberGetCcaThresholdReturn emApiGetCcaThresholdReturn
  #define emberGetChannelCalDataTokenReturn emApiGetChannelCalDataTokenReturn
  #define emberGetCommissioner emApiGetCommissioner
  #define emberGetCounter emApiGetCounter
  #define emberGetCounterReturn emApiGetCounterReturn
  #define emberGetCtune emApiGetCtune
  #define emberGetCtuneReturn emApiGetCtuneReturn
  #define emberGetGlobalAddresses emApiGetGlobalAddresses
  #define emberGetGlobalAddressReturn emApiGetGlobalAddressReturn
  #define emberGetGlobalPrefixes emApiGetGlobalPrefixes
  #define emberGetGlobalPrefixReturn emApiGetGlobalPrefixReturn
  #define emberGetIndexedToken emApiGetIndexedToken
  #define emberGetLocalIpAddress emApiGetLocalIpAddress
  #define emberGetMfgToken emApiGetMfgToken
  #define emberGetMfgTokenReturn emApiGetMfgTokenReturn
  #define emberGetMulticastEntryReturn emApiGetMulticastEntryReturn
  #define emberGetMulticastTable emApiGetMulticastTable
  #define emberGetNetworkData emApiGetNetworkData
  #define emberGetNetworkDataReturn emApiGetNetworkDataReturn
  #define emberGetNetworkDataTlv emApiGetNetworkDataTlv
  #define emberGetNetworkDataTlvReturn emApiGetNetworkDataTlvReturn
  #define emberGetNetworkKeyInfo emApiGetNetworkKeyInfo
  #define emberGetNetworkKeyInfoReturn emApiGetNetworkKeyInfoReturn
  #define emberGetNetworkParameters emApiGetNetworkParameters
  #define emberGetNodeStatus emApiGetNodeStatus
  #define emberGetNodeStatusReturn emApiGetNodeStatusReturn
  #define emberGetPanId emApiGetPanId
  #define emberGetPtaEnable emApiGetPtaEnable
  #define emberGetPtaEnableReturn emApiGetPtaEnableReturn
  #define emberGetPtaOptions emApiGetPtaOptions
  #define emberGetPtaOptionsReturn emApiGetPtaOptionsReturn
  #define emberGetRadioPower emApiGetRadioPower
  #define emberGetRadioPowerReturn emApiGetRadioPowerReturn
  #define emberGetRipEntry emApiGetRipEntry
  #define emberGetRipEntryReturn emApiGetRipEntryReturn
  #define emberGetRoutingLocator emApiGetRoutingLocator
  #define emberGetRoutingLocatorReturn emApiGetRoutingLocatorReturn
  #define emberGetSecureDtlsSessionId emApiGetSecureDtlsSessionId
  #define emberGetSecureDtlsSessionIdReturn emApiGetSecureDtlsSessionIdReturn
  #define emberGetStandaloneBootloaderInfo emApiGetStandaloneBootloaderInfo
  #define emberGetStandaloneBootloaderInfoReturn emApiGetStandaloneBootloaderInfoReturn
  #define emberGetTxPowerMode emApiGetTxPowerMode
  #define emberGetTxPowerModeReturn emApiGetTxPowerModeReturn
  #define emberGetVersions emApiGetVersions
  #define emberGetVersionsReturn emApiGetVersionsReturn
  #define emberGpioCurrentConfig emApiGpioCurrentConfig
  #define emberGpioCurrentConfigReturn emApiGpioCurrentConfigReturn
  #define emberGpioCurrentInput emApiGpioCurrentInput
  #define emberGpioCurrentInputReturn emApiGpioCurrentInputReturn
  #define emberGpioPowerConfig emApiGpioPowerConfig
  #define emberGpioPowerConfigReturn emApiGpioPowerConfigReturn
  #define emberGpioRadioPowerMask emApiGpioRadioPowerMask
  #define emberHostStateHandler emApiHostStateHandler
  #define emberHostToNcpNoOp emApiHostToNcpNoOp
  #define emberIcmpListen emApiIcmpListen
  #define emberIncomingIcmpHandler emApiIncomingIcmpHandler
  #define emberInit emApiInit
  #define emberInitHost emApiInitHost
  #define emberInitReturn emApiInitReturn
  #define emberIpPing emApiIpPing
  #define emberJoinCommissioned emApiJoinCommissioned
  #define emberJoinNetwork emApiJoinNetwork
  #define emberJoinNetworkReturn emApiJoinNetworkReturn
  #define emberLaunchStandaloneBootloader emApiLaunchStandaloneBootloader
  #define emberLaunchStandaloneBootloaderReturn emApiLaunchStandaloneBootloaderReturn
  #define emberLeaderDataHandler emApiLeaderDataHandler
  #define emberListenForWakeup emApiListenForWakeup
  #define emberListenForWakeupReturn emApiListenForWakeupReturn
  #define emberLookupAddressData emApiLookupAddressData
  #define emberLookupAddressDataReturn emApiLookupAddressDataReturn
  #define emberMacPassthroughFilterHandler emApiMacPassthroughFilterHandler
  #define emberMacPassthroughMessageHandler emApiMacPassthroughMessageHandler
  #define emberMacRssiFilterHandler emApiMacRssiFilterHandler
  #define emberMacRssiHandler emApiMacRssiHandler
  #define emberMarkApplicationBuffersHandler emApiMarkApplicationBuffersHandler
  #define emberNcpToHostNoOp emApiNcpToHostNoOp
  #define emberNcpUdpStorm emApiNcpUdpStorm
  #define emberNcpUdpStormCompleteHandler emApiNcpUdpStormCompleteHandler
  #define emberNcpUdpStormReturn emApiNcpUdpStormReturn
  #define emberNetworkDataChangeHandler emApiNetworkDataChangeHandler
  #define emberNetworkStatus emApiNetworkStatus
  #define emberNetworkStatusHandler emApiNetworkStatusHandler
  #define emberOkToNap emApiOkToNap
  #define emberOkToNapReturn emApiOkToNapReturn
  #define emberOpenDtlsConnection emApiOpenDtlsConnection
  #define emberOpenDtlsConnectionReturn emApiOpenDtlsConnectionReturn
  #define emberHostJoinClientComplete emApiHostJoinClientComplete
  #define emberPermitJoining emApiPermitJoining
  #define emberPermitJoiningHandler emApiPermitJoiningHandler
  #define emberPermitJoiningReturn emApiPermitJoiningReturn
  #define emberPing emApiPing
  #define emberPollForData emApiPollForData
  #define emberPollForDataReturn emApiPollForDataReturn
  #define emberRadioGetRandomNumbers emApiRadioGetRandomNumbers
  #define emberRadioGetRandomNumbersReturn emApiRadioGetRandomNumbersReturn
  #define emberRegisterDropIncomingMessageCallback emApiRegisterDropIncomingMessageCallback
  #define emberRegisterSerialTransmitCallback emApiRegisterSerialTransmitCallback
  #define emberRequestDhcpAddress emApiRequestDhcpAddress
  #define emberRequestDhcpAddressReturn emApiRequestDhcpAddressReturn
  #define emberRequestSlaacAddress emApiRequestSlaacAddress
  #define emberRequestSlaacAddressReturn emApiRequestSlaacAddressReturn
  #define emberResetIpDriverAsh emApiResetIpDriverAsh
  #define emberResetMicro emApiResetMicro
  #define emberResetMicroHandler emApiResetMicroHandler
  #define emberResetNcpAsh emApiResetNcpAsh
  #define emberResetNcpAshReturn emApiResetNcpAshReturn
  #define emberResetNcpGpio emApiResetNcpGpio
  #define emberResetNetworkState emApiResetNetworkState
  #define emberResetNetworkStateReturn emApiResetNetworkStateReturn
  #define emberResignGlobalAddress emApiResignGlobalAddress
  #define emberResignGlobalAddressReturn emApiResignGlobalAddressReturn
  #define emberResumeNetwork emApiResumeNetwork
  #define emberResumeNetworkReturn emApiResumeNetworkReturn
  #define emberRetryCoapMessage emApiRetryCoapMessage
  #define emberScanReturn emApiScanReturn
  #define emberSendDone emApiSendDone
  #define emberSendDoneReturn emApiSendDoneReturn
  #define emberSendSteeringData emApiSendSteeringData
  #define emberSendSteeringDataReturn emApiSendSteeringDataReturn
  #define emberSendUdp emApiSendUdp
  #define emberSetAddressHandler emApiSetAddressHandler
  #define emberSetCcaThreshold emApiSetCcaThreshold
  #define emberSetCcaThresholdReturn emApiSetCcaThresholdReturn
  #define emberSetClockMonitor emApiSetClockMonitor
  #define emberSetCommProxyAppAddressHandler emApiSetCommProxyAppAddressHandler
  #define emberSetCommProxyAppPskcHandler emApiSetCommProxyAppPskcHandler
  #define emberSetCommProxyAppParametersHandler emApiSetCommProxyAppParametersHandler
  #define emberSetCommProxyAppSecurityHandler emApiSetCommProxyAppSecurityHandler
  #define emberSetCommissionerKey emApiSetCommissionerKey
  #define emberSetCommissionerKeyReturn emApiSetCommissionerKeyReturn
  #define emberSetCtune emApiSetCtune
  #define emberSetCtuneReturn emApiSetCtuneReturn
  #define emberSetDriverAddressHandler emApiSetDriverAddressHandler
  #define emberSetDtlsDeviceCertificate emApiSetDtlsDeviceCertificate
  #define emberSetDtlsDeviceCertificateReturn emApiSetDtlsDeviceCertificateReturn
  #define emberSetDtlsPresharedKey emApiSetDtlsPresharedKey
  #define emberSetDtlsPresharedKeyReturn emApiSetDtlsPresharedKeyReturn
  #define emberSetEui64 emApiSetEui64
  #define emberSetAntennaMode emApiSetAntennaMode
  #define emberSetAntennaModeReturn emApiSetAntennaModeReturn
  #define emberSetJoiningMode emApiSetJoiningMode
  #define emberSetJoinKey emApiSetJoinKey
  #define emberSetJoinKeyReturn emApiSetJoinKeyReturn
  #define emberSetLegacyFilterMaxThreshold emApiSetLegacyFilterMaxThreshold
  #define emberSetLegacyFilterMaxThresholdReturn emApiSetLegacyFilterMaxThresholdReturn
  #define emberSetLegacyFilterMinThreshold emApiSetLegacyFilterMinThreshold
  #define emberSetLegacyFilterMinThresholdReturn emApiSetLegacyFilterMinThresholdReturn
  #define emberSetLocalNetworkData emApiSetLocalNetworkData
  #define emberSetLocalNetworkDataReturn emApiSetLocalNetworkDataReturn
  #define emberSetMfgToken emApiSetMfgToken
  #define emberSetMfgTokenReturn emApiSetMfgTokenReturn
  #define emberSetNdData emApiSetNdData
  #define emberSetNdDataReturn emApiSetNdDataReturn
  #define emberSetNetworkKeysHandler emApiSetNetworkKeysHandler
  #define emberSetNextNetworkKey emApiSetNextNetworkKey
  #define emberSetNextNetworkKeyReturn emApiSetNextNetworkKeyReturn
  #define emberSetPassthroughPort emApiSetPassthroughPort
  #define emberSetPskcHandler emApiSetPskcHandler
  #define emberSetPtaEnable emApiSetPtaEnable
  #define emberSetPtaEnableReturn emApiSetPtaEnableReturn
  #define emberSetPtaOptions emApiSetPtaOptions
  #define emberSetPtaOptionsReturn emApiSetPtaOptionsReturn
  #define emberSetRadioHoldOff emApiSetRadioHoldOff
  #define emberSetRadioHoldOffReturn emApiSetRadioHoldOffReturn
  #define emberSetRadioPower emApiSetRadioPower
  #define emberSetRadioPowerReturn emApiSetRadioPowerReturn
  #define emberSetRandomizeMacExtendedId emApiSetRandomizeMacExtendedId
  #define emberSetSecurityParameters emApiSetSecurityParameters
  #define emberSetSecurityParametersReturn emApiSetSecurityParametersReturn
  #define emberSetTxPowerMode emApiSetTxPowerMode
  #define emberSetTxPowerModeReturn emApiSetTxPowerModeReturn
  #define emberSetWakeupSequenceNumber emApiSetWakeupSequenceNumber
  #define emberSetWakeupSequenceNumberReturn emApiSetWakeupSequenceNumberReturn
  #define emberSlaacServerChangeHandler emApiSlaacServerChangeHandler
  #define emberSleepNoTimer emApiSleepNoTimer
  #define emberSleepNoTimerReturn emApiSleepNoTimerReturn
  #define emberStackIdleTimeMs emApiStackIdleTimeMs
  #define emberStackPollForData emApiStackPollForData
  #define emberStackPollForDataReturn emApiStackPollForDataReturn
  #define emberStartHostJoinClientHandler emApiStartHostJoinClientHandler
  #define emberStartScan emApiStartScan
  #define emberStartUartSpeedTest emApiStartUartSpeedTest
  #define emberStartUartStorm emApiStartUartStorm
  #define emberStartUartStormReturn emApiStartUartStormReturn
  #define emberStartWakeup emApiStartWakeup
  #define emberStartWakeupReturn emApiStartWakeupReturn
  #define emberStartXOnXOffTest emApiStartXOnXOffTest
  #define emberState emApiState
  #define emberStateReturn emApiStateReturn
  #define emberStopCommissioning emApiStopCommissioning
  #define emberStopScan emApiStopScan
  #define emberStopUartStorm emApiStopUartStorm
  #define emberStopUartStormReturn emApiStopUartStormReturn
  #define emberSwitchToNextNetworkKey emApiSwitchToNextNetworkKey
  #define emberSwitchToNextNetworkKeyHandler emApiSwitchToNextNetworkKeyHandler
  #define emberSwitchToNextNetworkKeyReturn emApiSwitchToNextNetworkKeyReturn
  #define emberTick emApiTick
  #define emberUartSpeedTestReturn emApiUartSpeedTestReturn
  #define emberUdpHandler emApiUdpHandler
  #define emberUdpListen emApiUdpListen
  #define emberUdpMulticastHandler emApiUdpMulticastHandler
  #define emberWakeupHandler emApiWakeupHandler
  #define emberWakeupState emApiWakeupState
  #define emberWakeupStateReturn emApiWakeupStateReturn
  #define mfglibEnd mfglibApiEnd
  #define mfglibGetChannel mfglibApiGetChannel
  #define mfglibGetOptions mfglibApiGetOptions
  #define mfglibGetPower mfglibApiGetPower
  #define mfglibGetPowerMode mfglibApiGetPowerMode
  #define mfglibGetSynOffset mfglibApiGetSynOffset
  #define mfglibSendPacket mfglibApiSendPacket
  #define mfglibSetChannel mfglibApiSetChannel
  #define mfglibSetOptions mfglibApiSetOptions
  #define mfglibSetPower mfglibApiSetPower
  #define mfglibSetSynOffset mfglibApiSetSynOffset
  #define mfglibStart mfglibApiStart
  #define mfglibStartStream mfglibApiStartStream
  #define mfglibStartTone mfglibApiStartTone
  #define mfglibStopStream mfglibApiStopStream
  #define mfglibStopTone mfglibApiStopTone
  #define mfglibTestContModCal mfglibApiTestContModCal
  #define emNoteExternalCommissioner emStackNoteExternalCommissioner
  #define emIpPing emStackIpPing
  #define tmspMfglibEnd tmspNcpMfglibEnd
  #define tmspMfglibEndTestReturn tmspNcpMfglibEndTestReturn
  #define tmspMfglibGet tmspNcpMfglibGet
  #define tmspMfglibGetChannelReturn tmspNcpMfglibGetChannelReturn
  #define tmspMfglibGetOptionsReturn tmspNcpMfglibGetOptionsReturn
  #define tmspMfglibGetPowerModeReturn tmspNcpMfglibGetPowerModeReturn
  #define tmspMfglibGetPowerReturn tmspNcpMfglibGetPowerReturn
  #define tmspMfglibGetSynOffsetReturn tmspNcpMfglibGetSynOffsetReturn
  #define tmspMfglibRxReturn tmspNcpMfglibRxReturn
  #define tmspMfglibSendPacket tmspNcpMfglibSendPacket
  #define tmspMfglibSendPacketEventHandler tmspNcpMfglibSendPacketEventHandler
  #define tmspMfglibSet tmspNcpMfglibSet
  #define tmspMfglibSetReturn tmspNcpMfglibSetReturn
  #define tmspMfglibStart tmspNcpMfglibStart
  #define tmspMfglibStartActivity tmspNcpMfglibStartActivity
  #define tmspMfglibStartReturn tmspNcpMfglibStartReturn
  #define tmspMfglibStartTestReturn tmspNcpMfglibStartTestReturn
  #define tmspMfglibStopActivity tmspNcpMfglibStopActivity
  #define tmspMfglibStopReturn tmspNcpMfglibStopReturn
  #define tmspMfglibTestContModCal tmspNcpMfglibTestContModCal

#endif

#endif // DEFINE_EMBER_API_H
