// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED.
// See the script gen-api-macro-header and read gen-api-macro-header.README.

#ifndef UNDEFINE_EMBER_API_H
#define UNDEFINE_EMBER_API_H

#if defined(RTOS) && defined(IP_MODEM_LIBRARY) // NCP thread in RTOS target

  #undef emberAbortWakeup
  #undef emberAbortWakeupReturn
  #undef emberActiveScanHandler
  #undef emberActiveWakeup
  #undef emberActiveWakeupReturn
  #undef emberAddAddressData
  #undef emberAddAddressDataReturn
  #undef emberAddressConfigurationChangeHandler
  #undef emberAddSteeringEui64
  #undef emberAllowNativeCommissioner
  #undef emberAllowNativeCommissionerReturn
  #undef emberAppEventQueue
  #undef emberAppEvents
  #undef emberAssertInfoReturn
  #undef emberAttachToNetwork
  #undef emberAttachToNetworkReturn
  #undef emberBecomeCommissioner
  #undef emberBecomeCommissionerReturn
  #undef emberChangeNodeType
  #undef emberChangeNodeTypeReturn
  #undef emberClearAddressCache
  #undef emberClearAddressCacheReturn
  #undef emberClearCounters
  #undef emberCloseDtlsConnection
  #undef emberCloseDtlsConnectionReturn
  #undef emberCoapMessageHandler
  #undef emberCoapRequestHandler
  #undef emberCommandTable
  #undef emberCommissionerStatusHandler
  #undef emberCommissionNetwork
  #undef emberCommissionNetworkReturn
  #undef emberConfigUart
  #undef emberConfigUartReturn
  #undef emberConfigureExternalRoute
  #undef emberConfigureExternalRouteReturn
  #undef emberConfigureGateway
  #undef emberConfigureGatewayReturn
  #undef emberConfigureNetwork
  #undef emberConfigureWakeup
  #undef emberCounterHandler
  #undef emberCounterValueHandler
  #undef emberCustomHostToNcpMessage
  #undef emberCustomHostToNcpMessageHandler
  #undef emberCustomNcpToHostMessage
  #undef emberCustomNcpToHostMessageHandler
  #undef emberDeepSleep
  #undef emberDeepSleepCompleteHandler
  #undef emberDeepSleepReturn
  #undef emberDhcpServerChangeHandler
  #undef emberDiagnosticAnswerHandler
  #undef emberDtlsSecureSessionEstablished
  #undef emberEcho
  #undef emberEchoReturn
  #undef emberEnableHostDtlsClient
  #undef emberEnableResetNcpGpio
  #undef emberEnergyScanHandler
  #undef emberEui64
  #undef emberEventDelayUpdatedFromIsrHandler
  #undef emberExternalRouteChangeHandler
  #undef emberFfWakeup
  #undef emberFinishCoapMessage
  #undef emberForceAssert
  #undef emberFormNetwork
  #undef emberFormNetworkReturn
  #undef emberGetAntennaMode
  #undef emberGetAntennaModeReturn
  #undef emberGetCcaThreshold
  #undef emberGetCcaThresholdReturn
  #undef emberGetChannelCalDataTokenReturn
  #undef emberGetCommissioner
  #undef emberGetCounter
  #undef emberGetCounterReturn
  #undef emberGetCtune
  #undef emberGetCtuneReturn
  #undef emberGetGlobalAddresses
  #undef emberGetGlobalAddressReturn
  #undef emberGetGlobalPrefixes
  #undef emberGetGlobalPrefixReturn
  #undef emberGetIndexedToken
  #undef emberGetLocalIpAddress
  #undef emberGetMfgToken
  #undef emberGetMfgTokenReturn
  #undef emberGetMulticastEntryReturn
  #undef emberGetMulticastTable
  #undef emberGetNetworkData
  #undef emberGetNetworkDataReturn
  #undef emberGetNetworkDataTlv
  #undef emberGetNetworkDataTlvReturn
  #undef emberGetNetworkKeyInfo
  #undef emberGetNetworkKeyInfoReturn
  #undef emberGetNetworkParameters
  #undef emberGetNodeStatus
  #undef emberGetNodeStatusReturn
  #undef emberGetPanId
  #undef emberGetPtaEnable
  #undef emberGetPtaEnableReturn
  #undef emberGetPtaOptions
  #undef emberGetPtaOptionsReturn
  #undef emberGetRadioPower
  #undef emberGetRadioPowerReturn
  #undef emberGetRipEntry
  #undef emberGetRipEntryReturn
  #undef emberGetRoutingLocator
  #undef emberGetRoutingLocatorReturn
  #undef emberGetSecureDtlsSessionId
  #undef emberGetSecureDtlsSessionIdReturn
  #undef emberGetStandaloneBootloaderInfo
  #undef emberGetStandaloneBootloaderInfoReturn
  #undef emberGetTxPowerMode
  #undef emberGetTxPowerModeReturn
  #undef emberGetVersions
  #undef emberGetVersionsReturn
  #undef emberGpioCurrentConfig
  #undef emberGpioCurrentConfigReturn
  #undef emberGpioCurrentInput
  #undef emberGpioCurrentInputReturn
  #undef emberGpioPowerConfig
  #undef emberGpioPowerConfigReturn
  #undef emberGpioRadioPowerMask
  #undef emberHostStateHandler
  #undef emberHostToNcpNoOp
  #undef emberIcmpListen
  #undef emberIncomingIcmpHandler
  #undef emberInit
  #undef emberInitHost
  #undef emberInitReturn
  #undef emberIpPing
  #undef emberJoinCommissioned
  #undef emberJoinNetwork
  #undef emberJoinNetworkReturn
  #undef emberLaunchStandaloneBootloader
  #undef emberLaunchStandaloneBootloaderReturn
  #undef emberLeaderDataHandler
  #undef emberListenForWakeup
  #undef emberListenForWakeupReturn
  #undef emberLookupAddressData
  #undef emberLookupAddressDataReturn
  #undef emberMacPassthroughFilterHandler
  #undef emberMacPassthroughMessageHandler
  #undef emberMacRssiFilterHandler
  #undef emberMacRssiHandler
  #undef emberMarkApplicationBuffersHandler
  #undef emberNcpToHostNoOp
  #undef emberNcpUdpStorm
  #undef emberNcpUdpStormCompleteHandler
  #undef emberNcpUdpStormReturn
  #undef emberNetworkDataChangeHandler
  #undef emberNetworkStatus
  #undef emberNetworkStatusHandler
  #undef emberOkToNap
  #undef emberOkToNapReturn
  #undef emberOpenDtlsConnection
  #undef emberOpenDtlsConnectionReturn
  #undef emberHostJoinClientComplete
  #undef emberPermitJoining
  #undef emberPermitJoiningHandler
  #undef emberPermitJoiningReturn
  #undef emberPing
  #undef emberPollForData
  #undef emberPollForDataReturn
  #undef emberRadioGetRandomNumbers
  #undef emberRadioGetRandomNumbersReturn
  #undef emberRegisterDropIncomingMessageCallback
  #undef emberRegisterSerialTransmitCallback
  #undef emberRequestDhcpAddress
  #undef emberRequestDhcpAddressReturn
  #undef emberRequestSlaacAddress
  #undef emberRequestSlaacAddressReturn
  #undef emberResetIpDriverAsh
  #undef emberResetMicro
  #undef emberResetMicroHandler
  #undef emberResetNcpAsh
  #undef emberResetNcpAshReturn
  #undef emberResetNcpGpio
  #undef emberResetNetworkState
  #undef emberResetNetworkStateReturn
  #undef emberResignGlobalAddress
  #undef emberResignGlobalAddressReturn
  #undef emberResumeNetwork
  #undef emberResumeNetworkReturn
  #undef emberRetryCoapMessage
  #undef emberScanReturn
  #undef emberSendDone
  #undef emberSendDoneReturn
  #undef emberSendSteeringData
  #undef emberSendSteeringDataReturn
  #undef emberSendUdp
  #undef emberSetAddressHandler
  #undef emberSetCcaThreshold
  #undef emberSetCcaThresholdReturn
  #undef emberSetClockMonitor
  #undef emberSetCommProxyAppAddressHandler
  #undef emberSetCommProxyAppPskcHandler
  #undef emberSetCommProxyAppParametersHandler
  #undef emberSetCommProxyAppSecurityHandler
  #undef emberSetCommissionerKey
  #undef emberSetCommissionerKeyReturn
  #undef emberSetCtune
  #undef emberSetCtuneReturn
  #undef emberSetDriverAddressHandler
  #undef emberSetDtlsDeviceCertificate
  #undef emberSetDtlsDeviceCertificateReturn
  #undef emberSetDtlsPresharedKey
  #undef emberSetDtlsPresharedKeyReturn
  #undef emberSetEui64
  #undef emberSetAntennaMode
  #undef emberSetAntennaModeReturn
  #undef emberSetJoiningMode
  #undef emberSetJoinKey
  #undef emberSetJoinKeyReturn
  #undef emberSetLegacyFilterMaxThreshold
  #undef emberSetLegacyFilterMaxThresholdReturn
  #undef emberSetLegacyFilterMinThreshold
  #undef emberSetLegacyFilterMinThresholdReturn
  #undef emberSetLocalNetworkData
  #undef emberSetLocalNetworkDataReturn
  #undef emberSetMfgToken
  #undef emberSetMfgTokenReturn
  #undef emberSetNdData
  #undef emberSetNdDataReturn
  #undef emberSetNetworkKeysHandler
  #undef emberSetNextNetworkKey
  #undef emberSetNextNetworkKeyReturn
  #undef emberSetPassthroughPort
  #undef emberSetPskcHandler
  #undef emberSetPtaEnable
  #undef emberSetPtaEnableReturn
  #undef emberSetPtaOptions
  #undef emberSetPtaOptionsReturn
  #undef emberSetRadioHoldOff
  #undef emberSetRadioHoldOffReturn
  #undef emberSetRadioPower
  #undef emberSetRadioPowerReturn
  #undef emberSetRandomizeMacExtendedId
  #undef emberSetSecurityParameters
  #undef emberSetSecurityParametersReturn
  #undef emberSetTxPowerMode
  #undef emberSetTxPowerModeReturn
  #undef emberSetWakeupSequenceNumber
  #undef emberSetWakeupSequenceNumberReturn
  #undef emberSlaacServerChangeHandler
  #undef emberSleepNoTimer
  #undef emberSleepNoTimerReturn
  #undef emberStackIdleTimeMs
  #undef emberStackPollForData
  #undef emberStackPollForDataReturn
  #undef emberStartHostJoinClientHandler
  #undef emberStartScan
  #undef emberStartUartSpeedTest
  #undef emberStartUartStorm
  #undef emberStartUartStormReturn
  #undef emberStartWakeup
  #undef emberStartWakeupReturn
  #undef emberStartXOnXOffTest
  #undef emberState
  #undef emberStateReturn
  #undef emberStopCommissioning
  #undef emberStopScan
  #undef emberStopUartStorm
  #undef emberStopUartStormReturn
  #undef emberSwitchToNextNetworkKey
  #undef emberSwitchToNextNetworkKeyHandler
  #undef emberSwitchToNextNetworkKeyReturn
  #undef emberTick
  #undef emberUartSpeedTestReturn
  #undef emberUdpHandler
  #undef emberUdpListen
  #undef emberUdpMulticastHandler
  #undef emberWakeupHandler
  #undef emberWakeupState
  #undef emberWakeupStateReturn
  #undef mfglibEnd
  #undef mfglibGetChannel
  #undef mfglibGetOptions
  #undef mfglibGetPower
  #undef mfglibGetPowerMode
  #undef mfglibGetSynOffset
  #undef mfglibSendPacket
  #undef mfglibSetChannel
  #undef mfglibSetOptions
  #undef mfglibSetPower
  #undef mfglibSetSynOffset
  #undef mfglibStart
  #undef mfglibStartStream
  #undef mfglibStartTone
  #undef mfglibStopStream
  #undef mfglibStopTone
  #undef mfglibTestContModCal
  #undef emNoteExternalCommissioner
  #undef emIpPing
  #undef tmspMfglibEnd
  #undef tmspMfglibEndTestReturn
  #undef tmspMfglibGet
  #undef tmspMfglibGetChannelReturn
  #undef tmspMfglibGetOptionsReturn
  #undef tmspMfglibGetPowerModeReturn
  #undef tmspMfglibGetPowerReturn
  #undef tmspMfglibGetSynOffsetReturn
  #undef tmspMfglibRxReturn
  #undef tmspMfglibSendPacket
  #undef tmspMfglibSendPacketEventHandler
  #undef tmspMfglibSet
  #undef tmspMfglibSetReturn
  #undef tmspMfglibStart
  #undef tmspMfglibStartActivity
  #undef tmspMfglibStartReturn
  #undef tmspMfglibStartTestReturn
  #undef tmspMfglibStopActivity
  #undef tmspMfglibStopReturn
  #undef tmspMfglibTestContModCal

#endif

#endif // UNDEFINE_EMBER_API_H
