#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Bluetooth stack headers
#include "bg_types.h"
#include "native_gecko.h"
#include "infrastructure.h"

// EM library (EMlib)
#include "em_system.h"
#include "em_gpio.h"

// Libraries containing default Gecko configuration values
#include "em_emu.h"
#include "em_cmu.h"

/* Device initialization header */
#include "hal-config.h"

#include "platform.h"

/**
 * Initialize hardware
 */
void hwInit()
{
  // Push button
  NVIC_EnableIRQ(GPIO_EVEN_IRQn);
  NVIC_EnableIRQ(GPIO_ODD_IRQn);
  GPIO_IntConfig(BSP_BUTTON0_PORT, BSP_BUTTON0_PIN, 0, 1, 1);
  GPIO_IntConfig(BSP_BUTTON1_PORT, BSP_BUTTON1_PIN, 0, 1, 1);
}

/**
 * Handle GPIO interrupts and trigger system_external_signal BGAPI event
 * which is handled in main loop. GPIO interrupt is generated by WSTK push button.
 */
void GPIO_Common_IRQHandler()
{
  uint32_t flags = GPIO_IntGet();
  GPIO_IntClear(flags);

  if (flags & (1 << BSP_BUTTON0_PIN)) {
    //Send interupt event to the main loop
    gecko_external_signal(SIGNAL_SWITCH_STACK0);
  }
  if (flags & (1 << BSP_BUTTON1_PIN)) {
    //Send interupt event to the main loop
    gecko_external_signal(SIGNAL_SWITCH_STACK1);
  }
}

void GPIO_EVEN_IRQHandler()
{
  GPIO_Common_IRQHandler();
}
void GPIO_ODD_IRQHandler()
{
  GPIO_Common_IRQHandler();
}
